### ISSUE TITLE
Virtual Board for Scenario #100 doesn't load

### ISSUE THREAD

**Issue by dhyanna** [PurpleKingdomGames/virtual-gloomhaven-board#81] opened 2021-11-04 22:52 UTC
**Affected Scenario(s):** [e.g. 6, 10 and 33]
100

**Describe the bug**
Selecting Scenario 100 in Virtual Board in gloomhaven-storyline.com loads a blank screen at this url: https://vgb.purplekingdomgames.com/?lockRoomCode=1&lockScenario=1&scenario=100&seed=175288107

When I Reload Scenario, it doesn't load scenario 100 but the last scenario I used even though the url still has 100 as one of its params

**Browser :** [e.g. Chrome, Firefox]
Chrome

**Comment by hobnob** [comment] 2021-11-05 09:48
This is a duplicate of #71 , though TBH the title doesn't really reflect the issue very clearly. The problem is that Scenario 100 is very complicated, and will need it's own set of rules to work out. Definitely on the list of things to do, but I'm not sure when I'll get around to it :-(

**Closed** 2021-11-05 09:48 UTC
Labels: bug

**Comment by dhyanna** [comment] 2021-11-05 16:26
Understandable, David. I get it. Thanks for responding.
