### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by dhyanna** [PurpleKingdomGames/virtual-gloomhaven-board#91] opened 2022-03-25 15:03 UTC
**Affected Scenario(s):** [e.g. 6, 10 and 33]
All

**Describe the bug**
I enter a scenario via gloomhaven-storyline.com and share the room code with friends. Everyone else can add and delete overlay tiles and can move characters and monsters and their modifications to the board are seen by everyone including myself. However, any action I take to modify the board is not shared with anyone else. When I click the browser reload button, there is a momentary popup on the board that says I'm offline and a link to Reconnect. But the notification disappears before I can click the link, and in the times I'm quick enough to do, clicking doesn't change anything. Why would be I be offline all the time while others are not.

**Browser :** [e.g. Chrome, Firefox]
Same with Chrome and Edge

**Comment by hobnob** [comment] 2022-05-16 07:34
Hi @dhyanna , sorry it's taken so long to get back to you things have been very hectic here 🙁  It doesn't look like you're offline (at least in the truest sense of the word), as the notification would be permanently set. I have a feeling this might be related to a long-standing issue (#76)... could you try Firefox and see if you suffer the same problem?

If you could send me some network packets (some that arrived and some sent) that would be great.. ideally the ones like the below:
![Screenshot 2022-05-16 at 08 32 19](https://user-images.githubusercontent.com/908784/168541618-8fef62b4-7c32-41e9-abce-245a1cb2e3da.png)
 
To access this go right click on a cell and click 'Inspect' then click on the network tab and filter on 'WS'

**Comment by dhyanna** [comment] 2022-05-16 18:39
I probably should have updated this ticket, but a few weeks ago I had the same thought and installed Firefox. The issue does *not* present itself while I'm using Firefox instead of Chrome or Edge. I've been using Firefox successfully for the past few sessions on several different scenarios.

I'm happy to continue to use Firefox. Do you still want the network packets?

**Comment by hobnob** [comment] 2022-06-08 06:52
Hi @dhyanna , Sorry it's been really busy here - back on it now though :) Let's leave it for now I'll mark this as closed, as a duplicate of #76

**Closed by hobnob** 2022-06-08 06:52 UTC
Labels: bug
