### ISSUE TITLE
Number/letter token overlays

### ISSUE THREAD

**Issue by DaniBodor** [PurpleKingdomGames/virtual-gloomhaven-board#60] opened 2020-12-28 21:09 UTC
A lot of scenarios have number or letter tokens that either remind you to read some story line or represent different special rules. These would be really good to have in the virtual bord as well, because they are often not easy to represent by the available options (we currently usually use summons or obstacles for this, but it becomes confusing pretty quickly).

Non-spoiler example for level 2: there's a number 1 on the door, which adds new rules to the scenario and wouldn't be noticed if you didn't loom into the scenario book.

Level 56 (spoiler alert) has a-tokens which represent allies and would also be missed if you don't look into the book.

Keep up the good work, it's a really great platform!!

**Comment by hobnob** [comment] 2020-12-28 21:41
Hi @DaniBodor,

Thanks for your feedback and sponsorship! I think this might be a duplicate of #14 , but puts it a bit better than I did there. We currently use Summons in our games too, and you're right it gets complicated quite quickly.

I'll have a look into this probably in the second-ish week of the new year, once solo scenarios are in and as part of the custom scenario creator work that I'll be doing at about the same time :-)

**Comment by orphu** [comment] 2021-01-14 13:19
Just to add, there are scenarios that have you adding terrain (like water tiles) as well. A general solution to add or remove overlay tiles is needed.

**Comment by hobnob** [comment] 2021-01-14 15:22
Hmmmm.. yeah looks like I'm going to need to add a few more overlays...do you know the scenarios that add terrain? Must have missed that when going through them :-/

**Comment by orphu** [comment] 2021-01-14 17:09
74 - Merchant Ship is one.

**Comment by orphu** [comment] 2021-01-28 16:11
Similarly, I see you have support for Forgotten Circles, but I don't see the Rift as an overlay option. These are overlays the diviner can create and move around.

**Comment by hobnob** [comment] 2021-01-28 16:26
Hi @orphu 

Thanks for the example. I'm planning on including water tiles in the next release, but at the moment I'm focussing a lot on the Scenario Creator so releases and bug fixes are a little delayed.

With regards to the Rift tokens, they should appear if there's a Diviner in your party. Otherwise they should be hidden :-) 

Hope that helps :-)

**Comment by orphu** [comment] 2021-01-28 18:55
> With regards to the Rift tokens, they should appear if there's a Diviner in your party. Otherwise they should be hidden :-)

Oh excellent! Thanks for the tip!

**Comment by hobnob** [comment] 2021-02-04 12:12
Hi @orphu ,

The water tile issue should be fixed now. Still need to add number tile overlays, but that will be available with or shortly after the Scenario Creator is ready :-)

**Comment by orphu** [comment] 2021-02-07 00:21
Looks great, thanks!

**Comment by hobnob** [comment] 2022-02-14 09:56
This I think is now fixed as of `1.14.0`

**Closed by hobnob** 2022-02-14 09:56 UTC
Labels: enhancement
